### ISSUE TITLE
Add support PhpStorm 2023.3 EAP

### ISSUE THREAD

**Issue by CrazyBoy49z** [sinchijackal/i18n-ally-plugin#1]
On MacBook, PhpStorm 2023.2 work correctly

**Comment by derwaldgeist** [comment]
No luck on WebStorm 2023.3 either.

**Comment by sinchijackal** [comment]
> No luck on WebStorm 2023.3 either.

The official i18n Ally plugin 1.4.2.1 now supports Webstorm versions 2023.2.1 — 2023.3.1
You can review it at the following link:
[https://plugins.jetbrains.com/plugin/17212-i18n-ally/versions/stable](https://plugins.jetbrains.com/plugin/17212-i18n-ally/versions/stable)
