### ISSUE TITLE
Add support to WebStorm 2024.2

### ISSUE THREAD

**Issue by nirtamir2** [sinchijackal/i18n-ally-plugin#2]
The fork works great! 
However, since a new WebStorm version is on the way, I’d like this plugin to be supported so that I can upgrade to WebStorm 2024.2. Can we support it?

![image](https://github.com/user-attachments/assets/d1e2ae4f-0447-4bdc-a0b9-603419bf6607)

**Comment by sinchijackal** [comment]
try with: https://github.com/sinchijackal/i18n-ally-plugin/releases/tag/1.4.2.4

**Comment by xzhimin** [comment]
https://github.com/sinchijackal/i18n-ally-plugin/releases/tag/1.4.2.4 The file  only supported 2024.1.x,No 2024.2.x version was updated
